name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da base de código
        uses: actions/checkout@v3.5.3
        
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
        
      - name: Construção da imagem da aplicação
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            lucastrindadedev/rotten-potatoes:${{ github.run_number }}
            lucastrindadedev/rotten-potatoes:latest
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout da base de código
        uses: actions/checkout@v3.5.3
        
      - name: Configurar as credenciais de acesso da AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configuração do Kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-east-1
      
      - name: Deploy da aplicação no cluster Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./deploy/app/deployment.yaml
          images: |
            lucastrindadedev/rotten-potatoes:${{ github.run_number }}

      - name: Deploy do mongodb no cluster Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./deploy/mongodb/deployment.yaml
          images: |
            mongo
